name: audit_cms
description: "Audit cms"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto_Bold.ttf

    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto_Medium.ttf

    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
