name: audit_cms
description: "Audit cms"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  flutter_speed_dial: ^7.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  syncfusion_flutter_pdfviewer: any
  downloads_path_provider_28: ^0.1.2
  file_picker: ^6.2.0
  jwt_decode: ^0.3.1
  infinite_scroll_pagination: ^4.0.0
  flutter_dotenv: ^5.1.0
  swipe_refresh: ^1.1.2
  device_info_plus: ^10.1.0
  currency_text_input_formatter: ^2.2.3
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/env/env_pro.env

  fonts:
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto_Bold.ttf

    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto_Medium.ttf

    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
